Repository Susmita-Dey/Moody-website, pull requests merged in 2022-10, with the labels that each got.

#15 added logo in readme.md
  README.md
Labels: documentation, hacktoberfest-accepted

#18 Changed UI of Contact section with some background illustrations
  assets/back_pattern.png
  index.html
Labels: enhancement, hacktoberfest-accepted

#22 Update index.html
  index.html
Labels: enhancement, hacktoberfest-accepted

#16 made the navbar responsive
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest-accepted

#28 Added issue_template for bug
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/other.yml
Labels: enhancement, hacktoberfest-accepted

#30 added smooth scrolling
  style.css
Labels: enhancement, hacktoberfest-accepted

#32 Hyperlinked the submit button.
  index.html
Labels: enhancement, hacktoberfest-accepted

#44 Added Favicon in the website head
  favicon_io/android-chrome-192x192.png
  favicon_io/android-chrome-512x512.png
  favicon_io/apple-touch-icon.png
  favicon_io/favicon-16x16.png
  favicon_io/favicon-32x32.png
  favicon_io/favicon.ico
  favicon_io/site.webmanifest
  index.html
Labels: enhancement, hacktoberfest-accepted

#43 enhanced the footer and added the links to the icons
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted

#46 Testimonials Header Introduced
  index.html
Labels: enhancement, hacktoberfest-accepted

#57 Improved the Responsiveness of the website(bug fix)
  style.css
Labels: bug, hacktoberfest-accepted

#73 Changed Footer UI
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted

#54 added images to testimonial section
  assets/testimonial-1.jpg
  assets/testimonial-2.jpg
  index.html
Labels: enhancement, hacktoberfest-accepted

#89 hyperlinked the email link correctly in footer
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted

#87 changed background of contact us section
  assets/contact-us.jpg
  index.html
Labels: enhancement, hacktoberfest-accepted

#100 update navbar section
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#102 update about section
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#95 Grammatical error in Testimonials #71
  index.html
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#96 Navigation bar is not auto hiding when click on home #70
  index.html
Labels: bug, hacktoberfest-accepted

#78 Contact Us Form Fix
  index.html
  script.js
Labels: enhancement, hacktoberfest-accepted

#94 Added animations and modified footer
  assets/mood.jpg
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted

#91 Updated the responsiveness of moody-website.
  style.css
Labels: enhancement, hacktoberfest-accepted

#93 Bottom to Top button has been added
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest-accepted

#113 Fixed the link in footer
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted

#114 Made the text in testimonial section clearly visible.
  index.html
Labels: enhancement, hacktoberfest-accepted

#112 Removed the unnecessary white space from top
  style.css
Labels: enhancement, hacktoberfest-accepted

#118 Improve navbar
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted

#120 Beautified the scroll bar
  style.css
Labels: enhancement, hacktoberfest-accepted

#121 Hover Effects
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted

#125 Update index.html
  index.html
Labels: bug, hacktoberfest-accepted

#127 Added a preloader
  assets/preload.gif
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted

#129 Fixes in index.html
  index.html
Labels: hacktoberfest-accepted

#130 Made the home page responsive
  style.css
Labels: bug, hacktoberfest-accepted
